#!/bin/bash

if [[ $EUID -ne 0 ]]; then  
    echo "$0 is not running as root. Use sudo."
    exit 2
fi

USER_HOME="/home/$SUDO_USER" 
HOME=$USER_HOME

tutorial() {
    echo " '$@' is not a valid option!!!!"
    echo "   type '-a' <groupname> to set additional groups"
    echo "   type '-u' <user> to set the username"
    echo "   type '-s' <shell> to set the shell"
    echo "   e.g. sudo ./newuser -a bluelock -u isagiyoichi -s /bin/bash"
    exit 1
}

PASSWORD=""
ADDITIONAL_GROUPS=""
USER=""
SHELL=""
E=""
while getopts ":a:u:s:" opt; do 
    case "{$opt}" in
    a) 
    ADDITIONAL_GROUPS=$OPTARG
    ;;
    u) 
    USERNAME=$OPTARG
    ;;
    s) 
    SHELL=$OPTARG
    ;;
    *) 
    tutorial
    ;;
    esac
done


if [[ -n $USER ]]; then
    useradd $USER -s $SHELL -d "~/assignment2" -g $USER

    if [ $? -eq 0 ]; then #Checks what the exit status it to find errors. I copied this from the manual of useradd (man useradd).
    echo "Success"
    elif [ $? -eq 1 ]; then
        echo "Can't update password file"
    elif [ $? -eq 2 ]; then
        echo "Invalid command syntax"
    elif [ $? -eq 3 ]; then
        echo "Invalid argument to option"
    elif [ $? -eq 4 ]; then
        echo "UID already in use (and no -o)"
    elif [ $? -eq 6 ]; then
        echo "Specified group doesn't exist"
    elif [ $? -eq 9 ]; then
        echo "Username or group name already in use"
    elif [ $? -eq 10 ]; then
        echo "Can't update group file"
    elif [ $? -eq 12 ]; then
        echo "Can't create home directory"
    elif [ $? -eq 14 ]; then
        echo "Can't update SELinux user mapping"
    fi


if [[ -n $USER]]; then 
    passwd $USER 

    if [ $? -eq 0 ]; then  #Checks what the exit status it to find errors. I copied this from the manual of passwd (man passwd).
    echo "Success"
    elif [ $? -eq 1 ]; then
        echo "Permission denied"
    elif [ $? -eq 2 ]; then
        echo "Invalid combination of options"
    elif [ $? -eq 3 ]; then
        echo "Unexpected failure, nothing done"
    elif [ $? -eq 4 ]; then
        echo "Unexpected failure, passwd file missing"
    elif [ $? -eq 5 ]; then
        echo "Passwd file busy, try again"
    elif [ $? -eq 6 ]; then
        echo "Invalid argument to option"
    fi
fi
